version: "3"

networks:
  app_net:
    driver: bridge
  nginx_net:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_net
  app:
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    command: gunicorn -b 0.0.0.0:5000 --access-logfile - --workers 1 --timeout 600 --reload app:app
    expose:
      - 5000
    networks:
      - app_net
      - nginx_net
